# REUSE Software Bill of Materials
# https://reuse.software/
version = 1
SPDX-PackageName = "zen-mcp-server"
SPDX-PackageSupplier = "Byron Williams"
SPDX-PackageDownloadLocation = "https://github.com/williaby/zen-mcp-server"

[[annotations]]
path = ["**"]
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileCopyrightText = "2025 Byron Williams"
