bias:
  complex_query_threshold_multiplier: 0.7
  enable_conservative_expansion: true
  error_context_boost: 0.2
  multi_domain_threshold_multiplier: 0.6
  new_user_threshold_multiplier: 0.6
calibration:
  calibration_curves:
    analysis:
      0.3: 0.5
      0.5: 0.65
      0.7: 0.8
      1.0: 0.9
    debug:
      0.3: 0.7
      0.5: 0.8
      0.7: 0.9
      1.0: 0.95
    git:
      0.3: 0.8
      0.5: 0.9
      0.7: 0.95
      1.0: 1.0
    quality:
      0.3: 0.6
      0.5: 0.7
      0.7: 0.85
      1.0: 0.9
    security:
      0.3: 0.7
      0.5: 0.8
      0.7: 0.9
      1.0: 0.95
    test:
      0.3: 0.6
      0.5: 0.75
      0.7: 0.85
      1.0: 0.9
  complexity_high_modifier: 0.8
  complexity_high_threshold: 0.8
  complexity_low_modifier: 1.1
  complexity_low_threshold: 0.3
  enable_calibration: true
category_modifiers:
  analysis_session_pattern: 1.1
  debug_context_errors: 1.3
  git_keyword_direct: 1.2
  security_context_files: 1.1
  test_environment_structure: 1.2
description: Task detection configuration for dynamic function loading
fallback:
  code_files_enable_quality: true
  default_strategy: context_based
  enable_context_adjustments: true
  expansion_category_limit: 3
  expansion_min_score: 0.2
  security_project_enables_security: true
  test_dirs_enable_testing: true
keywords:
  case_sensitive: false
  custom_patterns: {}
  enable_fuzzy_matching: false
  fuzzy_threshold: 0.8
  word_boundary_required: true
learning:
  accuracy_target_f1: 0.8
  enable_learning: true
  max_weight_change: 0.2
  min_samples_for_adaptation: 100
  pattern_history_limit: 1000
  user_pattern_limit: 1000
  weight_adaptation_rate: 0.1
mode: conservative
performance:
  cache_size: 1000
  cache_ttl_hours: 1
  enable_parallel_signals: true
  max_detection_time_ms: 50.0
  max_memory_usage_mb: 10
  signal_timeout_ms: 10.0
signal_weights:
  context_errors: 0.8
  context_files: 0.6
  context_performance: 0.7
  environment_git: 0.7
  environment_structure: 0.5
  keyword_action: 0.5
  keyword_contextual: 0.7
  keyword_direct: 1.0
  session_pattern: 0.8
  session_recent: 0.6
thresholds:
  ambiguous_difference_threshold: 0.15
  high_confidence_threshold: 0.9
  medium_confidence_threshold: 0.6
  tier2_base_threshold: 0.25
  tier3_base_threshold: 0.55
tier_definitions:
  tier1_categories:
  - core
  - git
  tier1_token_cost: 12300
  tier2_categories:
  - analysis
  - quality
  - debug
  - test
  - security
  tier2_token_cost: 19540
  tier3_categories:
  - external
  - infrastructure
  tier3_token_cost: 5800
version: 1.0.0
